var top = new Dictionary();
var left = new Dictionary();

function getCsvData(filename){
	var i;
	var line;
	var csv = new CSVParser();
	csv.initStorage(filename+".csv", true);
	for (i = 0; ;i++ ){
		line = csv.getNextLine();
		if(line == void){
			break;
		}		
		var name = filename+"_" + line[0];
		Debug.message(name);
		global.left[name] = line[1];
		global.top[name] = line[2];
	}
	invalidate csv;
}